blank_issues_enabled: false
contact_links:
  - name: Message me on LinkedIn
    url: https://www.linkedin.com/in/daniel-sambold-620b37221
    about: For anything you would rather not post in public. Email: daniel.sambold@gmail.com
  - name: My website
    url: https://dbold23.github.io
    about: The stories behind each project.
